LICENSE

Updated Kelp license

---

cmd/trade.go

Add current strategy to the log for later analysis. Change is to address issue https://github.com/lightyeario/kelp/issues/8

Print strat

---

api/exchange.go
plugins/factory.go
plugins/krakenExchange.go
plugins/krakenExchange_test.go

Kraken has very low API rate limits so we want to support rotation of API keys within Kraken.

Kraken rotate keys

---

cmd/trade.go
examples/configs/trader/sample_trader.cfg
trader/config.go
trader/trader.go

new trader config value: deleteCyclesThreshold

---

api/submitMode.go
cmd/trade.go
examples/configs/trader/sample_trader.cfg
model/orderbook.go
plugins/sdex.go
plugins/sdexMakerFilter.go
support/utils/functions.go
trader/config.go
trader/submitMode.go
trader/trader.go

Maker only mode

---

model/assets.go

Include USDC as an asset

---

api/exchange.go
cmd/terminate.go
cmd/trade.go
examples/configs/trader/sample_trader.cfg
model/assets.go
model/orderbook.go
plugins/balancedStrategy.go
plugins/batchedExchange.go
plugins/buysellStrategy.go
plugins/ccxtExchange.go
plugins/ccxtExchange_test.go
plugins/factory.go
plugins/ieif.go
plugins/krakenExchange.go
plugins/krakenExchange_test.go
plugins/mirrorStrategy.go
plugins/priceFeed.go
plugins/sdex.go
plugins/sdexFeed.go
plugins/sellSideStrategy.go
plugins/sellStrategy.go
support/sdk/ccxt.go
support/sdk/ccxt_test.go
support/utils/functions.go
trader/config.go
trader/trader.go

Enable centralized trading2

---

api/exchange.go
cmd/trade.go
plugins/batchedExchange.go
plugins/makerModeFilter.go
plugins/orderConstraintsFilter.go
plugins/sdexMakerFilter.go
trader/trader.go

Centralized maker only mode

---

cmd/trade.go
examples/configs/trader/sample_mirror.cfg
examples/configs/trader/sample_trader.cfg
plugins/ccxtExchange_test.go
plugins/mirrorStrategy.go
trader/config.go
trader/trader.go

ended up adding a new config field in trader.cfg and a new one in mirror.cfg when offsetTrades is enabled.

fix minVolume amounts when offsetting trades in mirror strategy, closes #136

---

cmd/trade.go
examples/configs/trader/sample_trader.cfg
support/sdk/ccxt.go
trader/config.go

closes https://github.com/stellar/kelp/issues/131

allow setting custom URL for CCXT-rest server

---

plugins/sdex.go

fix fill tracker to also work with path_payment type operations for sdex

---

plugins/sellSideStrategy.go

add triggers to modification log line in sdex

---

plugins/sellSideStrategy.go

new oversell trigger during modify to check need to reduce amount of existing offers

---

model/number.go
model/number_test.go

https://github.com/stellar/kelp/issues/264

improve number.AsRatio() conversion using stellar/go/price for more accurate pricing on centralized exchanges

---

gui/web/src/components/atoms/Input/Input.js
gui/web/src/components/molecules/Form/Form.js
gui/web/src/components/molecules/Levels/Levels.js

Fix handling of numeric fields, closes #218

---

gui/web/src/components/molecules/Form/Form.js

Kelp UI: Empty the asset issuer when asset code is XLM, closes #280

---

gui/backend/fetch_price.go
gui/backend/options_metadata.go
gui/web/src/components/_styles/variables.module.scss
gui/web/src/components/atoms/Label/Label.js
gui/web/src/components/atoms/Label/Label.module.scss
gui/web/src/components/molecules/FiatFeedAPIKey/FiatFeedAPIKey.js
gui/web/src/components/molecules/FiatFeedAPIKey/FiatFeedAPIKey.module.scss
gui/web/src/components/molecules/Form/Form.js
gui/web/src/components/molecules/PriceFeedDisplay/PriceFeedDisplay.js
gui/web/src/components/molecules/PriceFeedFormula/PriceFeedFormula.js
plugins/fiatFeed.go

Kelp UI: allow for a way to enter API key for fiat API, closes #221

---

LIST_OF_HACKS.md
README.md
examples/configs/trader/sample_trader.cfg
plugins/factory.go
support/networking/headerFn.go
support/networking/network.go
support/sdk/ccxt.go
support/sdk/headerFnMappings.go
support/utils/functions.go
support/utils/functions_test.go

Support dynamic CCXT headers for exchanges such as Coinbase

---

cmd/server_amd64.go
gui/backend/ping.go
gui/backend/routes.go
gui/windows-bat-file/kelp-start.bat
scripts/build.sh

still pending after this:
- run bash commands correctly (to create folders, start ccxt, start browser for --no-electron)
- ensure command prompt does not open up evert time we run a bash command

Kelp UI: add logic to package correctly for windows

---

cmd/root.go
cmd/trade.go
glide.lock
glide.yaml
scripts/build.sh
support/metrics/metricsTracker.go
trader/config.go
trader/trader.go

**What/Why**
This PR sets up Amplitude events for setup, update, and delete events. This will help enable data tracking for Kelp. This closes #478.

Set up CLI data tracking

---

plugins/volumeFilter.go
plugins/volumeFilter_test.go

This PR adds a test for the volume filter function (`volumeFilterFn`). It closes #483.

Add test for volume filter function (closes #483)

---

cmd/trade.go
examples/configs/trader/sample_trader.cfg
trader/config.go
trader/trader.go

Questions about technical design should be discussed before starting a PR. This can be discussed in the Github issue (preferred), or over IM (keybase / slack).
Typically, this is what is expected from the author of a Pull Request:
1. Each PR should correspond to the *smallest independent logical unit* of change.
- each PR should be prefixed with "bugfix", "feature", or "refactor".
- refactors should never be mixed in with logic changes or bug fixes and vice-versa.
- refactors that change variable names across more than 1 function should be a separate PR altogether.
1. Author should add inline commentary on the code changes to "guide" the reviewer on how to read the code change, highlighting key changes made.
- this should typically be 2-3 places, as anything bigger is too big of a PR and …

sleep mode, closes #606

---

plugins/volumeFilter_test.go

clean up remaining TODOs in volumeFilter_test.go

---

cmd/server_amd64.go
cmd/trade.go
gui/backend/send_metric_event.go
gui/web/src/App.js
gui/web/src/Constants.js
gui/web/src/components/atoms/Button/Button.js
gui/web/src/components/atoms/StartStop/StartStop.js
gui/web/src/components/molecules/BotCard/BotCard.js
gui/web/src/components/molecules/EmptyList/EmptyList.js
gui/web/src/components/molecules/Form/Form.js
gui/web/src/components/molecules/Header/Header.js
gui/web/src/components/molecules/Levels/Levels.js
gui/web/src/components/molecules/Modal/Modal.js
gui/web/src/components/molecules/PriceFeedAsset/PriceFeedAsset.js
gui/web/src/components/molecules/PriceFeedDisplay/PriceFeedDisplay.js
gui/web/src/components/molecules/ScreenHeader/ScreenHeader.js
gui/web/src/components/molecules/SecretKey/SecretKey.js
gui/web/src/components/molecules/Welcome/Welcome.js
gui/web/src/components/screens/Bots/Bots.js
gui/web/src/components/screens/Details/Details.js
gui/web/src/components/screens/NewBot/NewBot.js
gui/web/src/kelp-ops-api/sendMetricEvent.js
plugins/metricsTracker.go

related PR: https://github.com/stellar/kelp/pull/582

Add GUI metrics to Button.js and refactor metrics tracker and frontend metric architecture (part of #508)

---

plugins/ccxtExchange_test.go

This PR fixes the broken precision value test

fix broken precision value test

---

.circleci/config.yml
README.md
plugins/ccxtExchange_test.go
scripts/build.sh

This PR migrates Kelp from using glide to go modules for our dependency management
* Glide has been removed
* go.mod added
* Readme updated
* CircleCI updated

feat(277): upgrade dependency management go modules
