README.md, cmd/trade.go, examples/walkthroughs/trader/balanced.md, examples/walkthroughs/trader/buysell.md, examples/walkthroughs/trader/sell.md
Edit trade examples to clarify that the full path to the file is required.
The examples at present don't make it clear that the path to the _.cfg_ file is required for the config flags. This made it difficult for me as a new user to get started.
=> doc clarify full path needed for configs

README.md, accounting/pnl/pnl.go, api/exchange.go, cmd/trade.go, examples/configs/trader/sample_buysell.cfg, examples/configs/trader/sample_mirror.cfg, examples/configs/trader/sample_sell.cfg, model/assets.go, model/orderbook.go, model/tradingPair.go, plugins/buysellStrategy.go, plugins/ccxtExchange.go, plugins/ccxtExchange_test.go, plugins/exchangeFeed.go, plugins/factory.go, plugins/krakenExchange.go, plugins/krakenExchange_test.go, plugins/mirrorStrategy.go, plugins/priceFeed.go, plugins/sdex.go, plugins/sellStrategy.go, support/sdk/ccxt.go, support/sdk/ccxt_test.go, support/utils/network.go, terminator/terminator.go, trader/trader.go
This only implements enough of the CCXT exchange interface so it can be used as a priceFeed for the `sell` and `buysell` strategy, as well as fetching the orderbook so it can be used in the `mirror` strategy.
Currently it is only configured to support binance, poloniex, and bittrex.
=> Ccxt integration to support priceFeeds and orderbooks from multiple exchanges

.travis.yml, plugins/ccxtExchange_test.go, plugins/krakenExchange_test.go, support/monitoring/pagerDuty_test.go, support/sdk/ccxt_test.go
We make use of the `--short` flag when running go tests to disable certain tests that are unfeasible to run in a travis build.
=> Travis build runs existing tests, closes #57

.gitignore, cmd/trade.go, plugins/balancedLevelProvider.go
This implements a fill tracker for the balanced strategy that simply toggles a boolean for whether to regen levels. If no fills happen the existing levels will be re-submitted.
Addresses https://github.com/interstellar/kelp/issues/52
=> Add balanced fill tracking to avoid unecessary re-randomization

.travis.yml
needed since we have expanded CCXT integrations using the list of exchanges returned from the CCXT endpoint
=> fix travis build: update travis to launch ccxt in a docker image

api/exchange.go, cmd/trade.go, examples/configs/trader/sample_mirror.cfg, examples/configs/trader/sample_trader.cfg, model/orderbook.go, plugins/batchedExchange.go, plugins/ccxtExchange.go, plugins/krakenExchange.go, plugins/krakenExchange_test.go, plugins/mirrorStrategy.go, plugins/orderConstraintsOverridesHandler.go, plugins/sdex.go, support/utils/configs.go, trader/config.go, trader/trader.go
add override options to the config file.
renamed `MIN_CENTRALIZED_BASE_VOLUME` to `CENTRALIZED_MIN_BASE_VOLUME_OVERRIDE`
=> Override price vol precision and minQuoteVol, closes #141, closes #152

.gitignore, .travis.yml, README.md, api/exchange.go, cmd/terminate.go, cmd/trade.go, examples/configs/trader/sample_mirror.cfg, examples/configs/trader/sample_trader.cfg, glide.lock, glide.yaml, model/orderbook.go, model/tradingPair.go, plugins/batchedExchange.go, plugins/ccxtExchange.go, plugins/ccxtExchange_test.go, plugins/factory.go, plugins/ieif.go, plugins/krakenExchange.go, plugins/krakenExchange_test.go, plugins/mirrorStrategy.go, plugins/orderConstraintsOverridesHandler.go, plugins/sdex.go, plugins/sdexExtensions.go, support/prefs/prefs.go, support/sdk/ccxt.go, support/sdk/ccxt_test.go, support/utils/configs.go, trader/config.go, trader/trader.go
This pr implements the feature requested in https://github.com/stellar/kelp/issues/139 by allowing users to specify any additional ccxt parameters and/or http headers they may need to add to their API requests. I have live tested it on Coinbase Pro, so if this is implemented we can marked Coinbase Pro as tested.
=> Enable additional ccxt params and http headers

.semaphore/semaphore.yml
This PR aims to create an initial config for building and testing Kelp with Semaphore CI.
We're thinking about switching to Semaphore because it runs multiple builds in parallel, and it would greatly improve our workflow, especially in projects with many contributors such as the [Go monorepo](https://github.com/stellar/go).
**Note:** Once this PR gets merged, we'll need to do some setup on Semaphore to make sure it starts building stellar/kelp.
=> Build and test Kelp with Semaphore CI

.circleci/config.yml
This PR adds the necessary configuration for building and testing Kelp through Circle CI.
All builds and tests, for each Go version, are run in parallel, and the `node_modules` and `vendor` directories (for node.js and Go, respectively) are cached.
=> Add Circle CI support

api/exchange.go, api/strategy.go, cmd/terminate.go, cmd/trade.go, gui/backend/autogenerate_bot.go, gui/backend/upsert_bot_config.go, model/assets.go, model/botKey.go, plugins/balancedStrategy.go, plugins/batchedExchange.go, plugins/buysellStrategy.go, plugins/composeStrategy.go, plugins/deleteSideStrategy.go, plugins/deleteStrategy.go, plugins/factory.go, plugins/ieif.go, plugins/makerModeFilter.go, plugins/mirrorStrategy.go, plugins/orderConstraintsFilter.go, plugins/sdex.go, plugins/sdexFeed.go, plugins/sellSideStrategy.go, plugins/sellSideStrategy_test.go, plugins/sellStrategy.go, plugins/submitFilter.go, query/botInfo.go, support/utils/functions.go, trader/config.go, trader/trader.go
This PR covers part of the work required to update Kelp to use the new stellar Go sdk. This PR focuses on changing the types from `clients/horizon` to `protocols/horizon`.
This PR does not change all instances of `clients/horizon` types as there are some that is still needed by the old SDK. These will be handled in a separate PR when converting to the new `horizonclient` package.
=> Use horizon/protocol types

accounting/pnl/pnl.go, cmd/terminate.go, cmd/trade.go, plugins/priceFeed.go, plugins/sdex.go, plugins/sdexFeed.go, query/server.go, support/utils/functions.go, terminator/terminator.go, trader/trader.go
This PR covers part of the work required to update Kelp to use the new stellar Go sdk. This PR focuses on changing the horizon client package from `clients/horizon` to `clients/horizonclient`.
This PR does not change all usage of `clients/horizon` as there are some instances still needed by the old `build` Package.  In particular, these two files were not changed
- `.../gui/backend/upsert_bot_config.go`
- `.../gui/backend/autogenerate_bot.go`
These will be handled in a separate PR when converting to the new `txnbuild` package.
=> Use clients/horizonclient

plugins/sellSideStrategy.go
do not return an extra level for `numLevelsConsumed` because we may want to delete or modify it
fixes #250
=> fix op_underfunded error when replenishing top offer

README.md, gui/web/src/components/molecules/Welcome/Welcome.js
This PR updates the disclaimers in the `README` and GUI welcome page, based on conversations with SDF Legal. It closes #485. There are no known limitations.
=> Update disclaimers in README and welcome page (closes #485)

gui/backend/get_bot_info.go
This PR removes a call to `OSPath.String()` in the GUI backend. The call occurs because the error format invokes the `%s` format string on an `OSPath` variable as input. That calls Go's Stringer tool, which in turn invokes the `OSPath.String()` method. To avoid this, we now pass the result of `.AsString()` to the error formatter. This closes #430.
=> Remove OSPath.String() call in GUI backend (closes #430)

cmd/server_amd64.go, cmd/trade.go
**What**
This PR adds more granular Kelp app names. This directly implements the instructions in, and closes #488. 
**Why**
More granular app names will provide more visibility into the source of various requests, along multiple axes for analysis (GUI vs CLI, Desktop vs Browser).
**Known Limitations**
N/A
=> Add more granular Kelp app names (closes #488)

cmd/server_amd64.go, gui/backend/upsert_bot_config.go, gui/backend/upsert_bot_config_test.go
**What**
This PR disallows invalid characters in the bot name. The screenshot displays the fix, surfaced in the GUI. This closes #429.
**Why**
From #428: "When naming a bot with characters such as `<` and or` >` it attempts to create a file with that name and also remove that file when deleting which fails."
**Known limitations**
N/A
=> Disallow invalid characters in bot name (closes #429)

cmd/trade.go, glide.lock, glide.yaml, support/metrics/metricsTracker.go
This PR adds the device ID to the metric tracker's event properties. Part of #516.
Before: the device ID is the same as the user ID.
After: the device ID is library generated and distinct from the user ID.
=> Add device ID to metric event props (part of #516)

cmd/trade.go, support/metrics/metricsTracker.go, trader/trader.go
This PR sends the duration of the update event along with the metrics' common prop. Part of #516.
After: Can see `millisForUpdate` in Amplitude Web UI for an event.
=> Send update event execution duration with metrics (part of #516)

cmd/trade.go, support/sdk/ccxt.go, support/sdk/ccxt_test.go, support/utils/functions.go
This PR uses the hash of the bot's trading account as the user ID for metrics collection. If the user is using a centralized exchange, then it uses the hash of the Amplitude API key. Part of #516.
After: We see a different integer as the User ID from those previously used, on a build from this branch.
=> Use hashed trading account for metrics user ID (part of #516)

cmd/trade.go, support/metrics/metricsTracker.go
This PR disables metrics tracking if the `no-headers` flag is set to `true` in the CLI. Part of #516.
I confirmed this by setting the `userID=12345`, defining the API key, and running `kelp trade` with `no-headers=true`. I still got the expected log line on startup:
```metric - not sending event metric of type 'ce:test_startup' because metrics are disabled```
=> Disable metrics tracking with no headers (part of #516)

support/metrics/metricsTracker.go
This PR adds the `version` to the top-level metric event. Note that based on the [new API docs](https://help.amplitude.com/hc/en-us/articles/360032842391-HTTP-API-V2#tocSsuccesssummary), this requires serializing the `app_version` as the field in JSON. 
This shows the `version` surfaced in the web console:
=> Add version to metric event.

.circleci/config.yml, support/sdk/ccxt.go
improves mirror strategy by 20% (4.2s to 3.4s) and centralized exchange bots by a lot more
=> network speedup: check markets cache for existing symbols in ccxt.go#symbolExists(), closes #559

cmd/trade.go, support/metrics/metricsTracker.go
This PR adds some missing metrics to the CLI data tracking, using already-inputted values from the command line. This is part of #551. 
Subsequent PRs will add counters for the various metric events; hardware-based characteristics; and, later, a network event.
=> Add missing CLI metrics from inputs (part of #551)

api/exchange.go, plugins/metricsTracker.go, support/metrics/metricsTracker.go, trader/trader.go, trader/trader_test.go
This PR adds metrics for operation counts. It's marked as a draft PR because I have a few outstanding questions, and haven't fully tested it until these are resolved.
1. Does this implementation and architecture generally make sense?
2. Am I passing the correct parameters for prune ops and number of update ops in update?
3. Where is the number of update ops in delete supported to be? The only other len(ops) check in `trader/trader.go` is for deletion, but from the data doc, it looks like this count is for the update event, not deletion.
=> Add metrics for operation counts (part of #551)

plugins/volumeFilter_test.go
This PR modifies tests for the volume filter. Now, we test each combination of mode and action differently. Within a given mode/action combination, we test the four relationships of OTB and TBB values times the three ways the projected amount sold relates to the cap - giving us twelve possible cases.
Once this PR is merged, we'll add similar sets of twelve cases for the other mode/action combinations. (Note that these cases will not be identical, as changing the mode or action would result in different outputs.) This comprehensive approach allows us to safely regression test as we implement buy TWAP.
=> Modify tests for volume filter

plugins/volumeFilter_test.go
This PR adds the tests for `volumeFilterFn` when the quote cap is non-nil and the mode is `ignore`. This extends #611 to when the quote cap is non-nil, rather than when the base is. Follow-up PRs will deal with the `exact` mode.
=> Add volume filter tests for non-nil quote and ignore mode

plugins/volumeFilter.go, plugins/volumeFilter_test.go
This PR integrates tests for the buy-side for the volume filter, with the base cap and exact mode. Since we are keeping the test cases the same as the sell-side, this PR extends the existing function to also test base. It creates a buy operation with a different base asset; changes the asset used in `runTestVolumeFilterFn`; and loops over both actions in the test function.
To make the existing test cases all work, this also tweaks the `makeBuyOpSellAmt` and the logic around computing buy offers.
=> Test buy-side for volume filter with base cap and exact mode

plugins/volumeFilter_test.go
This PR adds all remaining buy-side tests for the volume filter function (`volumeFilterFn`). It extends #626 to the remaining combinations of filter mode and action.
=> Add all buy-side tests for volume filter

queries/dailyVolumeByDate_test.go
This PR adds buy-side tests for the daily volume queries. It patterns the existing test cases, and adds test data such that these patterned cases yield meaningful results.
=> Add buy tests for daily volume queries
